# fly.toml app configuration file generated for market-bot-toshiyuki2026 on 2026-04-06T03:49:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'market-bot-toshiyuki2026'
primary_region = 'nrt'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  # 'stop' を false に書き換え
  auto_stop_machines = false    
  auto_start_machines = true
  # 0 を 1 に書き換え（常に最低1台動かす）
  min_machines_running = 1      
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
